# Generated by Django 5.2.7 on 2025-10-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='FrutaDev', max_length=100),
        ),
    ]
